[package]
name = "replace_files"
version = "0.1.0"
authors = ["lumina00"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
