[package]
name = "file_encrypt"
version = "0.1.0"
authors = ["lumina00 <lumina.static@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ring = "^0.16.15"
